apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* 20 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: pragra/job
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          